Repository spoticks/FE_Spoticks, pull requests merged in 2024-09, with the labels that each got.

#32 모달 경로 변경
  db.json
  package-lock.json
  package.json
  src/MyTicketRoute.tsx
  src/Router.tsx
  src/assets/Barcode.svg
  src/components/Button.tsx
  src/components/CancellationConfirmModal.tsx
  src/components/Header/HeaderNav.tsx
  src/components/InformationCard.tsx
  src/components/InformationModal.tsx
  src/components/Loading.tsx
  src/components/MainMatch/MainMatch.tsx
  src/components/MenuButton.tsx
  src/constants.ts
  src/hooks/useHistoryModal.tsx
  src/main.tsx
  src/pages/CancellationHistory.tsx
  src/pages/InformationCard.tsx
  src/pages/MyHistory.tsx
  src/pages/MyReservations.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/Registration.tsx
  src/pages/matchList/MatchListMain.tsx
  src/pages/matchList/Tab.tsx
  src/type.ts
  tailwind.config.js
Labels: ✨  feat, ➕ add, 💄 design, 🔥 delete, 🚚 rename

#34 나의 팀 페이지 구현
  src/AuthRoute.tsx
  src/assets/baseballTeam/hanhwa_eagles.svg
  src/components/Header/Header.tsx
  src/components/Loading.tsx
  src/components/MyTeamList.tsx
  src/components/TeamLogo.tsx
  src/pages/MyTeam.tsx
Labels: ✨  feat, ➕ add, 💄 design, 🚚 rename

#35 myTeam과 payModal 생성 및 페이지들 경로변경
  db.json
  src/Router.tsx
  src/components/Admin/DetailModal.tsx
  src/components/Button.tsx
  src/components/PayModal.tsx
  src/components/matchList/HomeInfo.tsx
  src/components/matchList/MatchListMain.tsx
  src/components/matchList/MatchTabList.tsx
  src/components/matchList/MyTeamButton.tsx
  src/components/matchList/ReservationList.tsx
  src/components/matchList/ReserveInfo.tsx
  src/components/matchList/Tab.tsx
  src/components/seats/Section.tsx
  src/components/seats/SectionOfSeats.tsx
  src/components/seats/SelectedSeat.tsx
  src/pages/Admin.tsx
  src/pages/MatchList.tsx
  src/pages/Reservation.tsx
  src/pages/seats/Reservation.tsx
  src/pages/seats/Section.tsx
  src/type.ts
Labels: ✨  feat, 🚚 rename

#38 svg 컴포넌트화 및 절대경로 세팅
  package-lock.json
  package.json
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: ➕ add, 🔧 setting

#39 공통 컴포넌트 분리
  src/MyTicketRoute.tsx
  src/Router.tsx
  src/common/components/Layout/Footer.tsx
  src/common/components/Layout/Header/AuthButtonGroup.tsx
  src/common/components/Layout/Header/HeaderNav.tsx
  src/common/components/Layout/Header/MenuItem.tsx
  src/common/components/Layout/Header/UserButton.tsx
  src/common/components/Layout/Header/index.tsx
  src/common/components/Layout/index.tsx
  src/common/components/atoms/AppLogo.tsx
  src/common/components/atoms/Button.tsx
  src/common/components/atoms/Input.tsx
  src/common/components/atoms/InputErrorMessage.tsx
  src/common/components/atoms/Loading.tsx
  src/common/components/atoms/MenuButton.tsx
  src/common/components/atoms/ModalPortal.tsx
  src/common/components/atoms/SuccessToast.tsx
  src/common/components/atoms/TeamLogo.tsx
  src/common/components/atoms/TimeButton.tsx
  src/common/components/molecules/ConfirmAlert.tsx
  src/components/AccountDeletionForm.tsx
  src/components/Admin/DetailModal.tsx
  src/components/InformationModal.tsx
  src/components/MainMatch/MainMatchInfo/MainMatchInfo.tsx
  src/components/MainMatch/MainMatchInfo/MainMatchTeam.tsx
  src/components/MyTeamList.tsx
  src/components/PayModal.tsx
  src/components/UserInfo/BasicInfoField.tsx
  src/components/UserInfo/BasicUserInfo.tsx
  src/components/UserInfo/PasswordSetting.tsx
  src/components/WeeklyMatches/MatchCard/MatchCard.tsx
  src/components/matchList/MyTeamButton.tsx
  src/components/matchList/ReservationList.tsx
  src/components/seats/SelectedSeat.tsx
  src/pages/Admin.tsx
  src/pages/Login.tsx
  src/pages/MatchList.tsx
  src/pages/MyHistory.tsx
  src/pages/Reservation.tsx
  src/pages/SignUp.tsx
  src/pages/admin/Registration.tsx
Labels: 🚚 rename

#43 AccountDeletion 페이지 폴더 생성 및 컴포넌트 이동
  src/Router.tsx
  src/components/AccountDeletionForm.tsx
  src/hooks/usePopover.tsx
  src/pages/AccountDeletion/AccountDeletionForm/PasswordInput.tsx
  src/pages/AccountDeletion/AccountDeletionForm/ReasonSelect/DropdownButton.tsx
  src/pages/AccountDeletion/AccountDeletionForm/ReasonSelect/DropdownOptions.tsx
  src/pages/AccountDeletion/AccountDeletionForm/ReasonSelect/index.tsx
  src/pages/AccountDeletion/AccountDeletionForm/index.tsx
  src/pages/AccountDeletion/index.tsx
  src/type.ts
Labels: ✨  feat, 🚚 rename
