Repository spoticks/FE_Spoticks, pull requests merged in 2024-10, with the labels that each got.

#45 Login 페이지 폴더 생성 및 컴포넌트 이동, FormInputField 컴포넌트 생성
  src/Router.tsx
  src/common/components/atoms/Input.tsx
  src/common/components/atoms/InputErrorMessage.tsx
  src/common/components/molecules/FormInputField.tsx
  src/common/types/formTypes.ts
  src/common/types/type.ts
  src/components/Admin/DetailModal.tsx
  src/components/InformationCard.tsx
  src/components/PayModal.tsx
  src/components/matchList/MatchTabList.tsx
  src/components/matchList/ReservationList.tsx
  src/components/seats/Section.tsx
  src/components/seats/SectionOfSeats.tsx
  src/components/seats/SelectedSeat.tsx
  src/pages/AccountDeletion/AccountDeletionForm/PasswordInput.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/ReasonSelect/DropdownButton.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/ReasonSelect/DropdownOptions.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/ReasonSelect/index.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/index.tsx
  src/pages/AccountDeletion/index.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/TeamDisplay.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/index.tsx
  src/pages/Home/hooks/useTimer.tsx
  src/pages/Login.tsx
  src/pages/Login/api/useLoginMutation.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/index.tsx
  src/pages/MyHistory.tsx
  src/pages/Reservation.tsx
  src/pages/SignUp.tsx
  src/pages/admin/Registration.tsx
  src/stores/useStore.tsx
Labels: ✨  feat, ♻️ refactor, 🔥 delete, 🚚 rename

#49 MyHistory 및 MyPage 페이지 폴더 생성 및 컴포넌트 이동
  src/AuthRoute.tsx
  src/Router.tsx
  src/common/components/Layout/Header/UserButton.tsx
  src/common/components/Layout/Header/index.tsx
  src/common/components/Layout/index.tsx
  src/common/components/atoms/DefaultCard.tsx
  src/common/components/atoms/InputLabel.tsx
  src/common/components/molecules/FormInputField.tsx
  src/common/stores/authStore.tsx
  src/common/stores/myTeamStore.tsx
  src/common/stores/useStore.tsx
  src/common/types/formTypes.ts
  src/components/InformationModal.tsx
  src/components/MyTeamList.tsx
  src/components/PayModal.tsx
  src/components/UserInfo/BasicInfoField.tsx
  src/components/UserInfo/BasicUserInfo.tsx
  src/components/UserInfo/PasswordSetting.tsx
  src/components/matchList/MyTeamButton.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/ReasonSelect/index.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/index.tsx
  src/pages/Admin.tsx
  src/pages/ErrorPage.tsx
  src/pages/Login/api/useLoginMutation.tsx
  src/pages/MatchList.tsx
  src/pages/MyHistory.tsx
  src/pages/MyPage/components/BasicUserInfo/BasicUserInfoForm.tsx
  src/pages/MyPage/components/BasicUserInfo/index.tsx
  src/pages/MyPage/components/PasswordResetting/PasswordResettingForm.tsx
  src/pages/MyPage/components/PasswordResetting/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyTeam.tsx
  src/pages/MyTicket/api/useMyTicketHistory.tsx
  src/pages/MyTicket/components/InformationCard/index.tsx
  src/pages/MyTicket/components/MyTicketRouteLayout.tsx
  src/pages/MyTicket/index.tsx
  src/pages/Reservation.tsx
  src/pages/admin/Registration.tsx
Labels: ✨  feat, ♻️ refactor, 💄 design, 🔥 delete, 🚚 rename

#51 MyTeam 페이지 폴더 생성 및 컴포넌트 이동
  src/Router.tsx
  src/assets/RedHeart.svg
  src/common/api/useGetMyTeam.tsx
  src/common/api/useMyTeamDeletion.tsx
  src/common/types/type.ts
  src/components/MyTeamList.tsx
  src/pages/MyTeam/components/MyTeamList/MyTeamCard.tsx
  src/pages/MyTeam/components/MyTeamList/MyTeamDeletionButton.tsx
  src/pages/MyTeam/components/MyTeamList/index.tsx
  src/pages/MyTeam/index.tsx
Labels: ➕ add, 💄 design, 🚚 rename

#53 SignUp 페이지 폴더 생성 및 컴포넌트 이동
  src/Router.tsx
  src/common/components/AuthRoute.tsx
  src/common/components/Layout/Header/HeaderNav.tsx
  src/common/components/atoms/AuthFirstHeading.tsx
  src/common/components/atoms/AuthLinkButton.tsx
  src/common/constants.ts
  src/common/validationRules.ts
  src/components/matchList/MatchListMain.tsx
  src/components/matchList/MyTeamButton.tsx
  src/components/matchList/Tab.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/index.tsx
  src/pages/AccountDeletion/index.tsx
  src/pages/Admin.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/index.tsx
  src/pages/MatchList.tsx
  src/pages/MyPage/components/BasicUserInfo/BasicUserInfoForm.tsx
  src/pages/MyPage/components/PasswordResetting/PasswordResettingForm.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyTeam/index.tsx
  src/pages/MyTicket/components/MyTicketRouteLayout.tsx
  src/pages/SignUp.tsx
  src/pages/SignUp/api/onSubmitSignUpForm.ts
  src/pages/SignUp/components/SignUpForm.tsx
  src/pages/SignUp/index.tsx
  src/pages/admin/Registration.tsx
Labels: ✨  feat, 🔥 delete, 🚚 rename

#56 admin, matchList 폴더구조 변경 및 admin 페이지 컴포넌트 분리
  package-lock.json
  package.json
  src/Router.tsx
  src/common/components/atoms/InputLabel.tsx
  src/common/types/formTypes.ts
  src/pages/MatchList/components/HomeInfo.tsx
  src/pages/MatchList/components/MatchDetailMenu.tsx
  src/pages/MatchList/components/MatchListMain.tsx
  src/pages/MatchList/components/MyTeamButton.tsx
  src/pages/MatchList/components/ReservationList.tsx
  src/pages/MatchList/components/ReserveInfo.tsx
  src/pages/MatchList/components/Tab.tsx
  src/pages/MatchList/index.tsx
  src/pages/admin/Registration.tsx
  src/pages/admin/components/DetailModal.tsx
  src/pages/admin/components/RegiSchema.tsx
  src/pages/admin/components/Registration.tsx
  src/pages/admin/components/SelectField.tsx
  src/pages/admin/index.tsx
  src/pages/admin/type.ts
Labels: ✨  feat, ➕ add, 🚚 rename

#59 Modal 컴포넌트 리팩토링
  src/common/components/Layout/Header/index.tsx
  src/common/components/atoms/Loading.tsx
  src/common/components/molecules/InfoPart.tsx
  src/common/components/molecules/ModalHeader.tsx
  src/common/components/organisms/DetailedTicket.tsx
  src/common/components/organisms/ModalInfo.tsx
  src/common/utils/confirmAlert.ts
  src/common/utils/extractDateAndTime.ts
  src/common/utils/successToast.ts
  src/components/CancellationConfirmModal.tsx
  src/components/InformationModal.tsx
  src/components/PayModal.tsx
  src/hooks/useHistoryModal.tsx
  src/pages/Login/index.tsx
  src/pages/MyTicket/api/useMyTicketHistory.tsx
  src/pages/MyTicket/api/useReservationDetails.tsx
  src/pages/MyTicket/api/useTicketCancellationMutation.tsx
  src/pages/MyTicket/components/InformationCard/index.tsx
  src/pages/MyTicket/components/modal/CancellationConfirmModal/index.tsx
  src/pages/MyTicket/components/modal/InformationModal/index.tsx
  src/pages/MyTicket/index.tsx
  tailwind.config.js
Labels: ✨  feat, ♻️ refactor, 💄 design, 🔥 delete, 🚚 rename

#61 AxiosInstance 및 Interceptor 설정 + 타이틀 및 favicon 설정
  index.html
  src/common/utils/axiosInstance.ts
Labels: ✨  feat

#64 admin 페이지 수정중..
  db.json
  index.html
  src/common/components/atoms/ErrorToast.tsx
  src/common/components/atoms/ModalPortal.tsx
  src/common/constants.ts
  src/common/types/type.ts
  src/common/utils/confirmAlert.ts
  src/components/seats/SelectedSeat.tsx
  src/hooks/useAxios.tsx
  src/pages/admin/components/DetailModal.tsx
  src/pages/admin/components/Header.tsx
  src/pages/admin/components/Pagination.tsx
  src/pages/admin/components/RegiSchema.tsx
  src/pages/admin/components/Registration.tsx
  src/pages/admin/components/SelectField.tsx
  src/pages/admin/index.tsx
  src/pages/admin/type.ts
  src/pages/admin/util/useRegistrationForm.ts
Labels: ✨  feat, ♻️ refactor

#65 Login 페이지 수정
  src/common/components/Layout/Header/UserButton.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/MenuItem.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/index.tsx
  src/common/components/Layout/Header/UserButton/index.tsx
  src/common/components/Layout/Header/index.tsx
  src/common/components/molecules/FormInputField.tsx
  src/common/stores/authStore.tsx
  src/common/types/formTypes.ts
  src/common/utils/alertToast.ts
  src/common/utils/axiosInstance.ts
  src/common/utils/basicToast.ts
  src/common/utils/errorToast.tsx
  src/common/utils/successToast.ts
  src/common/validationRules.ts
  src/common/validationSchema.ts
  src/components/PayModal.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/index.tsx
  src/pages/Login/api/useLoginMutation.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/components/BasicUserInfo/BasicUserInfoForm.tsx
  src/pages/MyPage/components/PasswordResetting/PasswordResettingForm.tsx
  src/pages/SignUp/components/SignUpForm.tsx
  src/pages/SignUp/index.tsx
  src/pages/admin/components/DetailModal.tsx
  src/pages/admin/util/useRegistrationForm.ts
Labels: ✨  feat, 💄 design, 🔥 delete, 🚚 rename

#66 ♻️ refactor: admin페이지 폴더이동및 리팩토링 #63
  src/common/components/molecules/InfoPart.tsx
  src/common/constants.ts
  src/pages/admin/components/DetailModal.tsx
  src/pages/admin/components/RegiSchema.ts
  src/pages/admin/components/Registration.tsx
  src/pages/admin/components/atoms/DetailInfo.tsx
  src/pages/admin/components/atoms/Header.tsx
  src/pages/admin/components/atoms/Pagination.tsx
  src/pages/admin/components/atoms/SelectField.tsx
  src/pages/admin/index.tsx
Labels: ✨  feat, ♻️ refactor
