Repository spoticks/FE_Spoticks, pull requests merged in 2024-11, with the labels that each got.

#72 Header 컴포넌트 수정
  src/common/components/Layout/Footer.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/MenuItem.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/PopupMenu/PopupMenuList.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/PopupMenu/getPopupMenuItems.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/index.tsx
  src/common/components/Layout/Header/index.tsx
  src/common/components/Layout/index.tsx
  src/common/components/atoms/AppLogo.tsx
  src/common/stores/authStore.tsx
  src/common/types/type.ts
  src/common/utils/isValidMemberId.ts
  src/pages/MatchList/index.tsx
  tailwind.config.js
Labels: ✨  feat, 💄 design, 🚚 rename

#73 회원가입 구현
  src/common/api/useGetMyTeam.ts
  src/common/api/useMyTeamDeletion.ts
  src/common/components/atoms/Input.tsx
  src/common/components/atoms/InputErrorMessage.tsx
  src/common/components/atoms/InputMessage.tsx
  src/common/components/molecules/FormInputField.tsx
  src/common/types/formTypes.ts
  src/common/utils/alertToast.ts
  src/common/validationSchema.ts
  src/pages/Home/hooks/useDragScroll.ts
  src/pages/Home/hooks/useTimer.ts
  src/pages/Login/api/useLoginMutation.ts
  src/pages/MyTicket/api/useMyTicketHistory.ts
  src/pages/MyTicket/api/useReservationDetails.ts
  src/pages/MyTicket/api/useTicketCancellationMutation.ts
  src/pages/SignUp/api/onSubmitSignUpForm.ts
  src/pages/SignUp/api/useSignUpMutation.ts
  src/pages/SignUp/components/SignUpForm.tsx
  src/pages/SignUp/utils/useDuplicationCheck.ts
  src/pages/admin/components/atoms/SelectField.tsx
  tailwind.config.js
Labels: ✨  feat, 💄 design, 🔥 delete, 🚚 rename

#77 로그인 수정
  package-lock.json
  package.json
  src/common/components/Layout/Header/UserButton/UserInfoPopup/index.tsx
  src/common/components/Layout/Header/index.tsx
  src/common/components/atoms/AppLogo.tsx
  src/common/stores/authStore.tsx
  src/common/utils/isValidMemberId.ts
  src/hooks/useMemberInfo.tsx
  src/pages/Login/api/useLoginMutation.ts
Labels: ✨  feat, ➕ add, 🔥 delete

#76 MatchList Page router 재설정, 폴더구조변경, 컴포넌트 재사용
  src/Router.tsx
  src/common/components/atoms/button/MenuButton.tsx
  src/common/utils/errorToast.ts
  src/common/utils/getTeamId.ts
  src/pages/MatchList/api/api.ts
  src/pages/MatchList/components/Main.tsx
  src/pages/MatchList/components/MatchDetailMenu.tsx
  src/pages/MatchList/components/ReservationList.tsx
  src/pages/MatchList/components/ui/MatchDetailMenu.tsx
  src/pages/MatchList/components/ui/MyTeamButton.tsx
  src/pages/MatchList/components/ui/Tab.tsx
  src/pages/MatchList/components/ui/TdComp.tsx
  src/pages/MatchList/index.tsx
  src/pages/admin/components/Registration.tsx
  src/pages/admin/util/useRegistrationForm.ts
Labels: ✨  feat, ♻️ refactor, 🚚 rename

#78 회원정보 수정 구현
  src/common/components/Layout/Header/UserButton/UserInfoPopup/index.tsx
  src/common/components/Layout/Header/index.tsx
  src/common/components/atoms/AppLogo.tsx
  src/common/types/formTypes.ts
  src/common/validationSchema.ts
  src/hooks/useMemberInfo.tsx
  src/pages/MyPage/api/useGetMemberInfo.ts
  src/pages/MyPage/api/usePasswordResettingMutation.ts
  src/pages/MyPage/api/useUpdatePhoneNumberMutation.ts
  src/pages/MyPage/components/BasicUserInfo/BasicUserInfoForm.tsx
  src/pages/MyPage/components/PasswordResetting/PasswordResettingForm.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/utils/formatPhoneNumber.ts
  src/pages/SignUp/utils/useDuplicationCheck.ts
Labels: ✨  feat, 💄 design, 🔥 delete

#80 회원 탈퇴 로직 구현
  src/common/validationSchema.ts
  src/pages/AccountDeletion/api/useAccountDeletion.ts
  src/pages/AccountDeletion/components/AccountDeletionForm/ReasonSelect/index.tsx
  src/pages/AccountDeletion/components/AccountDeletionForm/index.tsx
  src/pages/MyPage/api/usePasswordResettingMutation.ts
  src/pages/MyPage/utils/formatPhoneNumber.ts
Labels: ✨  feat, 🔥 delete

#82 ♻️ refactor: matchList page 더보기버튼 수정중 #70
  src/pages/MatchList/api/api.ts
  src/pages/MatchList/components/ReservationList.tsx
  src/pages/MatchList/components/ui/MatchDetailMenu.tsx
  src/pages/MatchList/index.tsx
Labels: ♻️ refactor

#85 마이 팀 페이지 구현
  src/assets/cryingface.svg
  src/assets/smilingface.svg
  src/common/api/useGetMyTeam.ts
  src/common/api/useMyTeamDeletion.ts
  src/common/components/Layout/Header/index.tsx
  src/common/types/type.ts
  src/pages/AccountDeletion/index.tsx
  src/pages/MyTeam/components/MyTeamList/EmptyTeamList.tsx
  src/pages/MyTeam/components/MyTeamList/MyTeamCard/MyTeamDeletionButton.tsx
  src/pages/MyTeam/components/MyTeamList/MyTeamCard/index.tsx
  src/pages/MyTeam/components/MyTeamList/index.tsx
  src/pages/MyTeam/index.tsx
Labels: ✨  feat, 🔥 delete

#86 전역 에러 설정 및 에러 바운더리, 서스펜스 설정 및 기타 레이아웃 변경
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/assets/sirendanger.svg
  src/common/api/useGetMyTeam.ts
  src/common/components/AuthLayout/hooks/useContent.ts
  src/common/components/AuthLayout/index.tsx
  src/common/components/AuthLayout/utils/getContent.ts
  src/common/components/AuthRoute.tsx
  src/common/components/Layout/index.tsx
  src/common/components/atoms/Loading.tsx
  src/pages/AccountDeletion/index.tsx
  src/pages/ErrorPage.tsx
  src/pages/MyPage/api/useGetMemberInfo.ts
  src/pages/MyPage/components/BasicUserInfo/BasicUserInfoForm.tsx
  src/pages/MyPage/components/BasicUserInfo/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyTeam/components/MyTeamList/EmptyTeamList.tsx
  src/pages/MyTeam/components/MyTeamList/index.tsx
  src/pages/MyTeam/index.tsx
  src/pages/MyTicket/api/useMyTicketHistory.ts
  src/pages/MyTicket/components/MyTicketRouteLayout.tsx
  src/pages/MyTicket/index.tsx
Labels: ✨  feat, 💄 design, 🔥 delete, 🚚 rename

#88 MathListPage 예매내역 페이지 및 더보기버튼 활성화
  src/pages/MatchList/api/api.ts
  src/pages/MatchList/api/useMyTeamPost.ts
  src/pages/MatchList/components/ReservationList.tsx
  src/pages/MatchList/components/ui/MatchDetailMenu.tsx
  src/pages/MatchList/components/ui/MyTeamButton.tsx
  src/pages/MatchList/components/ui/Tab.tsx
  src/pages/MatchList/index.tsx
Labels: ✨  feat, ♻️ refactor

#89 예매 내역 페이지
  package-lock.json
  package.json
  src/App.tsx
  src/assets/calendar-delete.svg
  src/common/buttonStyles.ts
  src/common/components/AuthLayout/utils/getContent.ts
  src/common/components/Layout/index.tsx
  src/common/components/atoms/DefaultCard.tsx
  src/common/components/organisms/DetailedTicket.tsx
  src/common/types/type.ts
  src/common/utils/basicToast.ts
  src/pages/MyTicket/api/useMyTicketHistory.ts
  src/pages/MyTicket/api/useReservationDetails.ts
  src/pages/MyTicket/api/useTicketCancellationMutation.ts
  src/pages/MyTicket/components/InformationCard/index.tsx
  src/pages/MyTicket/components/NoTicketHistory.tsx
  src/pages/MyTicket/components/modal/InformationModal/InformationDetail.tsx
  src/pages/MyTicket/components/modal/InformationModal/index.tsx
  src/pages/MyTicket/hooks/useInfiniteScroll.ts
  src/pages/MyTicket/index.tsx
Labels: ✨  feat, ➕ add, 💄 design, 🔥 delete

#92 메인 페이지 구현
  src/assets/cone.svg
  src/assets/warning.svg
  src/common/components/Layout/index.tsx
  src/common/components/atoms/TeamLogo.tsx
  src/common/components/molecules/MatchDate.tsx
  src/common/types/type.ts
  src/common/utils/isGameDatePast.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/Home/api/useMainMatch.ts
  src/pages/Home/api/useMatchWeather.ts
  src/pages/Home/api/useWeeklyMatch.ts
  src/pages/Home/components/MainMatch/MainMatchContent.tsx
  src/pages/Home/components/MainMatch/MainMatchInfo/MainMatchTeam.tsx
  src/pages/Home/components/MainMatch/MainMatchInfo/index.tsx
  src/pages/Home/components/MainMatch/TicketOffSale.tsx
  src/pages/Home/components/MainMatch/Timer.tsx
  src/pages/Home/components/MainMatch/index.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/MatchDateInfo.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/TeamDisplay.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/WeeklyMatchTeam.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/index.tsx
  src/pages/Home/components/WeeklyMatches/WeeklyMatchList/DragScrollContainer.tsx
  src/pages/Home/components/WeeklyMatches/WeeklyMatchList/NoWeeklyMatch.tsx
  src/pages/Home/components/WeeklyMatches/WeeklyMatchList/index.tsx
  src/pages/Home/components/WeeklyMatches/index.tsx
  src/pages/Home/index.tsx
  src/pages/Home/utils/formatDate.ts
  src/pages/Home/utils/isSaleTimeOn.ts
  src/pages/MyTicket/api/useReservationDetails.ts
  src/pages/MyTicket/index.tsx
Labels: ✨  feat, 💄 design, 🔥 delete, 🚚 rename

#94 MyTeamButton Suspense로 감싸고 Reservation 페이지 폴더구조변경
  src/Router.tsx
  src/common/stores/myTeamStore.tsx
  src/common/utils/getTeamId.ts
  src/pages/MatchList/components/ui/MatchDetailMenu.tsx
  src/pages/Reservation/components/PayModal.tsx
  src/pages/Reservation/components/seats/Section.tsx
  src/pages/Reservation/components/seats/SectionOfSeats.tsx
  src/pages/Reservation/components/seats/SelectedSeat.tsx
  src/pages/Reservation/index.tsx
  src/pages/Reservation/type.ts
  src/pages/admin/index.tsx
Labels: ♻️ refactor, 🔥 delete, 🚚 rename
