Repository spoticks/FE_Spoticks, pull requests merged in 2024-12, with the labels that each got.

#96 기본적인 에러 핸들링 및 Footer 구현
  src/App.tsx
  src/assets/github-mark.svg
  src/common/components/Layout/Footer.tsx
  src/common/components/Layout/Footer/Copyright.tsx
  src/common/components/Layout/Footer/GithubLink.tsx
  src/common/components/Layout/Footer/index.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/index.tsx
  src/common/constants.ts
  src/common/utils/errorHandler.ts
  src/common/utils/getErrorToastMessage.ts
  src/hooks/useHistoryModal.ts
  src/hooks/useLogout.ts
  src/hooks/usehandleAuthError.ts
  src/pages/MyPage/api/useMemberPhoneNumberQuery.ts
  src/pages/MyPage/components/BasicUserInfo/BasicUserInfoForm.tsx
Labels: ✨  feat, ➕ add, 💄 design, 🔥 delete, 🚚 rename

#97 파일명 및 위치 변경, 기타 수정
  src/common/api/useMyTeamDeleteMutation.ts
  src/common/api/useMyTeamQuery.ts
  src/common/components/AuthLayout/hooks/useContent.ts
  src/common/components/AuthLayout/hooks/useHeaderDescription.ts
  src/common/components/AuthLayout/index.tsx
  src/common/components/AuthLayout/utils/getHeaderDescription.ts
  src/common/components/Layout/Footer/index.tsx
  src/common/components/atoms/MatchDate.tsx
  src/common/components/organisms/DetailedTicket.tsx
  src/common/types/type.ts
  src/common/utils/basicToast.ts
  src/common/utils/extractDateAndTime.ts
  src/common/utils/extractDateData.ts
  src/common/validationRules.ts
  src/hooks/useMemberInfo.ts
  src/hooks/usePopover.ts
  src/hooks/usehandleAuthError.ts
  src/pages/AccountDeletion/api/useAccountDeleteMutation.ts
  src/pages/AccountDeletion/components/AccountDeletionForm/index.tsx
  src/pages/Home/api/useMatchWeatherQuery.ts
  src/pages/Home/components/MainMatch/MainMatchContent.tsx
  src/pages/Home/components/MainMatch/MainMatchInfo/MainMatchTeam.tsx
  src/pages/Home/components/MainMatch/MainMatchInfo/index.tsx
  src/pages/Home/components/MainMatch/Timer.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/MatchDateInfo.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/WeeklyMatchTeam.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/index.tsx
  src/pages/Home/hooks/useMatchWeatherIconCode.ts
  src/pages/Home/hooks/useTimer.ts
  src/pages/Home/utils/calculateLeftTime.ts
  src/pages/Home/utils/formatDate.ts
  src/pages/MatchList/components/ui/MyTeamButton.tsx
  src/pages/MyTeam/components/MyTeamList/MyTeamCard/MyTeamDeletionButton.tsx
  src/pages/MyTeam/components/MyTeamList/index.tsx
  src/pages/MyTicket/api/useMyTicketHistoryQuery.ts
  src/pages/MyTicket/api/useReservationDetailQuery.ts
  src/pages/MyTicket/api/useReservationDetails.ts
  src/pages/MyTicket/components/InformationCard/index.tsx
  src/pages/MyTicket/components/modal/InformationModal/InformationDetail.tsx
  src/pages/MyTicket/hooks/useInfoModal.ts
  src/pages/MyTicket/hooks/useReservationDetails.ts
  src/pages/MyTicket/index.tsx
Labels: ✨  feat, 💄 design, 🔥 delete, 🚚 rename

#98 타입 정리
  src/common/api/useMyTeamQuery.ts
  src/common/components/organisms/DetailedTicket.tsx
  src/common/types/matchTypes.ts
  src/common/types/seatTypes.ts
  src/common/types/type.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/Home/api/useMainMatch.ts
  src/pages/Home/api/useWeeklyMatch.ts
  src/pages/Home/components/MainMatch/index.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/index.tsx
  src/pages/Home/components/WeeklyMatches/WeeklyMatchList/index.tsx
  src/pages/MatchList/api/api.ts
  src/pages/MatchList/components/ReservationList.tsx
  src/pages/MatchList/components/ui/MatchDetailMenu.tsx
  src/pages/MatchList/components/ui/Tab.tsx
  src/pages/MatchList/index.tsx
  src/pages/MyTicket/api/useMyTicketHistoryQuery.ts
  src/pages/MyTicket/api/useReservationDetailQuery.ts
  src/pages/MyTicket/components/InformationCard/index.tsx
  src/pages/Reservation/components/PayModal.tsx
  src/pages/Reservation/components/seats/Section.tsx
  src/pages/Reservation/components/seats/SectionOfSeats.tsx
  src/pages/Reservation/components/seats/SelectedSeat.tsx
  src/pages/Reservation/index.tsx
  src/pages/admin/components/DetailModal.tsx
  src/pages/admin/components/Registration.tsx
  src/pages/admin/index.tsx
  src/pages/admin/util/useRegistrationForm.ts
Labels: ✨  feat

#101 ErrorBoundary 수정 및 기타 수정사항
  src/assets/closedEye.svg
  src/assets/openEye.svg
  src/common/buttonStyles.ts
  src/common/components/AuthLayout/index.tsx
  src/common/components/Layout/index.tsx
  src/common/components/atoms/CustomErrorBoundary.tsx
  src/common/components/atoms/Input.tsx
  src/hooks/useExcludeHeaderFooter.ts
  src/index.css
  src/pages/AccountDeletion/components/AccountDeletionForm/index.tsx
  src/pages/Home/api/useMainMatch.ts
  src/pages/Home/api/useWeeklyMatchQuery.ts
  src/pages/Home/components/MainMatch/MainMatchInfo/index.tsx
  src/pages/Home/components/MainMatch/index.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/index.tsx
  src/pages/Home/components/WeeklyMatches/WeeklyMatchList/index.tsx
  src/pages/Home/components/WeeklyMatches/index.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/index.tsx
  src/pages/MatchList/components/ui/MatchDetailMenu.tsx
  src/pages/MyPage/components/BasicUserInfo/BasicUserInfoForm.tsx
  src/pages/MyPage/components/BasicUserInfo/index.tsx
  src/pages/MyPage/components/PasswordResetting/PasswordResettingForm.tsx
  src/pages/MyTicket/components/modal/InformationModal/InformationDetail.tsx
  src/pages/MyTicket/components/modal/InformationModal/index.tsx
  src/pages/SignUp/components/SignUpForm.tsx
  src/pages/SignUp/index.tsx
Labels: ✨  feat, 💄 design, 🔥 delete

#102 Admin 페이지 경기목록 무한스크롤 적용, type 정리, useAxios및 페이지네이션 삭제
  src/common/types/matchTypes.ts
  src/common/utils/axiosInstance.ts
  src/hooks/useAxios.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/Reservation/api/useReservationQuery.tsx
  src/pages/Reservation/index.tsx
  src/pages/admin/api/useAdminData.ts
  src/pages/admin/api/useRegistration.ts
  src/pages/admin/components/DetailModal.tsx
  src/pages/admin/components/RegiSchema.ts
  src/pages/admin/components/Registration.tsx
  src/pages/admin/components/ui/Pagination.tsx
  src/pages/admin/components/ui/RegisteredMatchList.tsx
  src/pages/admin/components/ui/TbodyComp.tsx
  src/pages/admin/index.tsx
  src/pages/admin/type.ts
Labels: 🐛 fix, ♻️ refactor, 🔥 delete

#103 인증 로직 수정
  db.json
  package-lock.json
  package.json
  src/App.tsx
  src/common/components/Layout/Header/UserButton/UserInfoPopup/index.tsx
  src/common/components/organisms/AuthProvider.tsx
  src/common/stores/authStore.ts
  src/common/stores/useStore.ts
  src/common/types/matchTypes.ts
  src/common/utils/axiosInstance.ts
  src/common/utils/errorHandler.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useLogout.ts
  src/hooks/useLogoutMutation.ts
  src/pages/Home/components/MainMatch/MainMatchContent.tsx
  src/pages/Home/components/MainMatch/MainMatchInfo/index.tsx
  src/pages/admin/api/useAdminData.ts
  src/pages/admin/api/useRegistration.ts
  src/pages/admin/components/DetailModal.tsx
  src/pages/admin/components/Registration.tsx
  src/pages/admin/components/ui/RegisteredMatchList.tsx
  src/pages/admin/components/ui/TbodyComp.tsx
Labels: ✨  feat, 🔥 delete, 🚚 rename

#106 🐛 fix: 배포 오류사항 수정 105
  src/common/stores/useStore.ts
  src/pages/MatchList/components/HomeInfo.tsx
  src/pages/MatchList/components/ReservationList.tsx
  src/pages/MatchList/components/ui/MatchDetailMenu.tsx
  src/pages/MatchList/components/ui/Tab.tsx
  src/pages/MatchList/index.tsx
  src/pages/MatchList/utils/getAddress.tsx
  src/pages/Reservation/components/PayModal.tsx
  src/pages/Reservation/index.tsx
Labels: 🐛 fix

#113 admin: 폴더구조변경, 페이지네이션 적용, 선택시간 단위 변경
  package-lock.json
  package.json
  src/Router.tsx
  src/pages/Registration/components/CustomTimePicker.tsx
  src/pages/Registration/components/SelectField.tsx
  src/pages/Registration/hooks/useRegistrationForm.ts
  src/pages/Registration/index.tsx
  src/pages/Registration/validation/RegiSchema.ts
  src/pages/admin/api/useAdminData.ts
  src/pages/admin/components/DetailModal/DetailInfo.tsx
  src/pages/admin/components/DetailModal/index.tsx
  src/pages/admin/components/RegisteredMatches/Header.tsx
  src/pages/admin/components/RegisteredMatches/MatchListBody.tsx
  src/pages/admin/components/RegisteredMatches/Pagination.tsx
  src/pages/admin/components/RegisteredMatches/TableSportFilter.tsx
  src/pages/admin/components/RegisteredMatches/index.tsx
  src/pages/admin/components/hooks/useAdminData.ts
  src/pages/admin/components/ui/RegisteredMatchList.tsx
  src/pages/admin/components/ui/TbodyComp.tsx
  src/pages/admin/index.tsx
  tailwind.config.js
Labels: ✨  feat, 🐛 fix, ♻️ refactor, 🚚 rename
