Repository spoticks/FE_Spoticks, pull requests merged in 2024-08, with the labels that each got.

#10 경기목록 페이지 및 공통 컴포넌트 (버튼) 생성
  src/Router.tsx
  src/assets/Heart.svg
  src/assets/TapClose.svg
  src/assets/TapOpen.svg
  src/assets/Tennis.svg
  src/assets/baseball.svg
  src/assets/basketball.svg
  src/assets/homeIcon.svg
  src/assets/infoIcon.svg
  src/assets/matchListTap.svg
  src/assets/reserveIcon.svg
  src/assets/soccer.svg
  src/assets/volleyball.svg
  src/components/Button.tsx
  src/pages/MatchList.tsx
  src/pages/Reservation.tsx
  src/pages/matchList/HomeInfo.tsx
  src/pages/matchList/MatchList.tsx
  src/pages/matchList/MatchListMain.tsx
  src/pages/matchList/ReservationList.tsx
  src/pages/matchList/ReserveInfo.tsx
Labels: ✨  feat, ➕ add, 🐛 fix

#12 헤더 컴포넌트 프로토타입 구현 #11
  src/Layout.tsx
  src/components/Button.tsx
  src/components/Header.tsx/Header.tsx
  src/components/Header.tsx/HeaderNav.tsx
  src/components/Logo.tsx
Labels: ✨  feat, 🐛 fix, 💄 design

#13 관리자 페이지 생성
  .eslintrc.cjs
  src/Router.tsx
  src/assets/Tickets.svg
  src/pages/Admin.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/Registration.tsx
  src/pages/matchList/MatchList.tsx
  src/pages/matchList/MatchListMain.tsx
Labels: ✨  feat

#14 헤더 스타일링 수정
  src/components/Header.tsx/Header.tsx
Labels: 💄 design

#15 풋터 컴포넌트 프로토타입 구현
  src/Layout.tsx
  src/components/Footer.tsx
Labels: ✨  feat

#16 경기등록페이지 수정
  src/pages/admin/Admin.tsx
  src/pages/admin/Registration.tsx
  src/stores/useStore.tsx
Labels: ✨  feat

#18 인풋 컴포넌트 프로토타입 구현
  src/components/Input.tsx
  src/hooks/useInput.ts
  tailwind.config.js
Labels: ✨  feat, ➕ add, 💄 design

#19 경기예매페이지 프로토타입 구현
  src/pages/Reservation.tsx
  src/pages/matchList/MatchList.tsx
  src/pages/matchList/ReservationList.tsx
  src/stores/useStore.tsx
Labels: ✨  feat, 🐛 fix, 💄 design

#20 admin 페이지 경기상세정보 모달 추가
  db.json
  package-lock.json
  package.json
  src/pages/admin/Admin.tsx
  src/pages/admin/DetailModal.tsx
  src/pages/admin/Registration.tsx
  src/stores/useStore.tsx
  src/type.ts
Labels: ✨  feat, ➕ add, 💄 design

#21 Home 컴포넌트 프로토타입 구현
  src/Layout.tsx
  src/assets/Tickets.svg
  src/assets/baseballTeam/doosan-bears.svg
  src/assets/baseballTeam/hanhwa_eagles.svg
  src/assets/baseballTeam/kia-tigers.svg
  src/assets/baseballTeam/kiwoom-heros.svg
  src/assets/baseballTeam/kt-wiz.svg
  src/assets/baseballTeam/lg-twins.svg
  src/assets/baseballTeam/lotte-giants.svg
  src/assets/baseballTeam/nc-dinos.svg
  src/assets/baseballTeam/samsung-lions.svg
  src/assets/baseballTeam/ssg-landers.svg
  src/assets/icons8-sun.svg
  src/components/Button.tsx
  src/components/Header.tsx/Header.tsx
  src/components/MainMatch/MainMatch.tsx
  src/components/MainMatch/MainMatchInfo/MainMatchInfo.tsx
  src/components/MainMatch/MainMatchInfo/MainMatchTeam.tsx
  src/components/MainMatch/Timer.tsx
  src/components/MenuButton.tsx
  src/components/TeamLogo.tsx
  src/components/WeeklyMatches/MatchCard/MatchCard.tsx
  src/components/WeeklyMatches/WeeklyMatches.tsx
  src/index.css
  src/pages/Home.tsx
  src/type.ts
  tailwind.config.js
Labels: ✨  feat, ➕ add, 💄 design, 🔥 delete, 🚚 rename

#22 admin 페이지 db.json 연결
  db.json
  src/Router.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/DetailModal.tsx
  src/pages/admin/Registration.tsx
  src/stores/useStore.tsx
  src/type.ts
Labels: ✨  feat, 🎨 style

#24 Login 페이지 프로토타입 구현
  src/components/Button.tsx
  src/components/Input.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/validationRules.ts
Labels: ✨  feat, 🔥 delete, 🚚 rename

#25 경기목록페이지 탭 연결 및 수정
  src/Router.tsx
  src/assets/baseball.svg
  src/assets/basketball.svg
  src/components/Header.tsx/HeaderNav.tsx
  src/components/constants.ts
  src/pages/admin/Admin.tsx
  src/pages/admin/Registration.tsx
  src/pages/matchList/MatchList.tsx
  src/pages/matchList/MatchListDetail.tsx
  src/pages/matchList/MatchListMain.tsx
  src/pages/matchList/ReservationList.tsx
  src/pages/matchList/Tab.tsx
  src/type.ts
Labels: ✨  feat, 🎨 style

#26 tanstackQuery 적용 및 실패페이지 생성
  src/App.tsx
  src/assets/NotFound.svg
  src/assets/Return.svg
  src/assets/TabClose.svg
  src/assets/TabOpen.svg
  src/assets/homeIcon.svg
  src/assets/spinner.svg
  src/components/Loading.tsx
  src/pages/NotFound.tsx
  src/pages/Reservation.tsx
  src/pages/admin/Admin.tsx
  src/pages/matchList/Tab.tsx
Labels: ✨  feat, 🐛 fix, 🎨 style, 💄 design

#27 MyPage 페이지 임시 구현
  db.json
  package-lock.json
  package.json
  src/App.tsx
  src/AuthRoute.tsx
  src/Router.tsx
  src/components/Button.tsx
  src/components/Header.tsx/AuthButtonGroup.tsx
  src/components/Header.tsx/Header.tsx
  src/components/Header.tsx/MenuItem.tsx
  src/components/Header.tsx/UserButton.tsx
  src/components/Input.tsx
  src/components/UserInfo/BasicInfoField.tsx
  src/components/UserInfo/BasicUserInfo.tsx
  src/components/UserInfo/InputLabel.tsx
  src/components/UserInfo/PasswordSetting.tsx
  src/hooks/useInput.ts
  src/hooks/usePopover.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/MyTickets.tsx
  src/stores/authStore.tsx
  src/validationRules.ts
Labels: ✨  feat, ➕ add, 🔥 delete

#28 회원 탈퇴 페이지 임시 구현
  src/Layout.tsx
  src/Router.tsx
  src/assets/heroicons_ticket-solid.svg
  src/components/AccountDeletionForm.tsx
  src/components/Button.tsx
  src/components/Header/AuthButtonGroup.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderNav.tsx
  src/components/Header/MenuItem.tsx
  src/components/Header/UserButton.tsx
  src/components/UserInfo/BasicUserInfo.tsx
  src/components/UserInfo/InputLabel.tsx
  src/hooks/usePopover.tsx
  src/pages/AccountDeletion.tsx
  src/pages/MyPage.tsx
  tailwind.config.js
Labels: ✨  feat, ➕ add, 💄 design, 🔥 delete

#30 예매 티켓 내역 확인 페이지 구현
  src/MyTicketRoute.tsx
  src/Router.tsx
  src/components/Header/UserButton.tsx
  src/components/MenuButton.tsx
  src/pages/CancellationHistory.tsx
  src/pages/InformationCard.tsx
  src/pages/MyReservations.tsx
  src/pages/MyTeam.tsx
  src/pages/MyTickets.tsx
  tailwind.config.js
Labels: ✨  feat, 💄 design, 🔥 delete
