Repository spoticks/FE_Spoticks, pull requests merged in 2025-01, with the labels that each got.

#114 로그인 로직 변경 및 기타 수정사항들
  src/App.tsx
  src/Router.tsx
  src/common/api/useMyTeamDeleteMutation.ts
  src/common/api/useMyTeamQuery.ts
  src/common/components/Layout/Header/index.tsx
  src/common/components/atoms/AppLogo.tsx
  src/common/components/atoms/Input.tsx
  src/common/components/organisms/AuthProvider.tsx
  src/common/layouts/AuthLayout/hooks/useHeaderDescription.ts
  src/common/layouts/AuthLayout/index.tsx
  src/common/layouts/AuthLayout/utils/getHeaderDescription.ts
  src/common/layouts/Layout/Footer/Copyright.tsx
  src/common/layouts/Layout/Footer/GithubLink.tsx
  src/common/layouts/Layout/Footer/index.tsx
  src/common/layouts/Layout/Header/AuthButtonGroup.tsx
  src/common/layouts/Layout/Header/HeaderNav.tsx
  src/common/layouts/Layout/Header/UserButton/UserInfoPopup/MenuItem.tsx
  src/common/layouts/Layout/Header/UserButton/UserInfoPopup/PopupMenu/PopupMenuList.tsx
  src/common/layouts/Layout/Header/UserButton/UserInfoPopup/PopupMenu/getPopupMenuItems.tsx
  src/common/layouts/Layout/Header/UserButton/UserInfoPopup/index.tsx
  src/common/layouts/Layout/Header/UserButton/index.tsx
  src/common/layouts/Layout/Header/index.tsx
  src/common/layouts/Layout/index.tsx
  src/common/routes/PrivateRoute.tsx
  src/common/stores/authStore.ts
  src/common/utils/axiosInstance.ts
  src/hooks/useMemberInfo.ts
  src/index.css
  src/pages/Home/components/MainMatch/MainMatchContent.tsx
  src/pages/Home/components/MainMatch/MainMatchInfo/index.tsx
  src/pages/Home/components/MainMatch/Timer.tsx
  src/pages/Home/components/MainMatch/index.tsx
  src/pages/Login/index.tsx
  src/pages/MatchList/api/useMyTeamPost.ts
  src/pages/MatchList/components/ui/MyTeamButton.tsx
  src/pages/MyTeam/components/EmptyTeamList.tsx
  src/pages/MyTeam/components/MyTeamCard/MyTeamDeletionButton.tsx
  src/pages/MyTeam/components/MyTeamCard/index.tsx
  src/pages/MyTeam/components/MyTeamList/index.tsx
  src/pages/MyTeam/index.tsx
  src/pages/SignUp/index.tsx
  tailwind.config.js
Labels: ✨  feat, ♻️ refactor, 💄 design, 🔥 delete, 🚚 rename

#115 MatchList 페이지 폴더 구조 변경 및 예매하기 버튼 변경, 페이지네이션 적용 및 기타 오류수정
  src/Router.tsx
  src/common/components/atoms/button/TimeButton.tsx
  src/common/components/molecules/Pagination.tsx
  src/common/utils/extractDateData.ts
  src/pages/MatchList/api/useMatch.ts
  src/pages/MatchList/api/useMatchApi.ts
  src/pages/MatchList/components/HomeInfo/RenderMap.tsx
  src/pages/MatchList/components/HomeInfo/index.tsx
  src/pages/MatchList/components/Main.tsx
  src/pages/MatchList/components/MatchDetailMenu/MyTeamButton.tsx
  src/pages/MatchList/components/MatchDetailMenu/index.tsx
  src/pages/MatchList/components/MatchListTab.tsx
  src/pages/MatchList/components/ReservationGuide/index.tsx
  src/pages/MatchList/components/ReservationList.tsx
  src/pages/MatchList/components/ReservationList/TableCell.tsx
  src/pages/MatchList/components/ReservationList/TableHeader.tsx
  src/pages/MatchList/components/ReservationList/index.tsx
  src/pages/MatchList/components/ui/Tab.tsx
  src/pages/MatchList/components/ui/TdComp.tsx
  src/pages/MatchList/index.tsx
  src/pages/Registration/hooks/useRegistrationForm.ts
  src/pages/Reservation/index.tsx
  src/pages/admin/components/DetailModal/index.tsx
  src/pages/admin/components/RegisteredMatches/index.tsx
Labels: ✨  feat, 🐛 fix, 🎨 style, ♻️ refactor, 🚚 rename

#116 로고 추가
  src/Router.tsx
  src/assets/basketballTeam/db_promy.svg
  src/assets/basketballTeam/jungkwanjang_redboosters.svg
  src/assets/basketballTeam/kcc_egis.svg
  src/assets/basketballTeam/lg_sakers.svg
  src/assets/basketballTeam/sk_knights.svg
  src/assets/footballTeam/daegu_fc.svg
  src/assets/footballTeam/gwangju_fc.svg
  src/assets/footballTeam/incheon_united.svg
  src/assets/footballTeam/jeju_united.svg
  src/assets/footballTeam/jeonbook_hyundai.svg
  src/assets/footballTeam/pohang_steelers.svg
  src/assets/footballTeam/seoul_fc.svg
  src/assets/footballTeam/suwon_samsung.svg
  src/assets/footballTeam/ulsan_hyundai.svg
  src/assets/volleyballTeam/deahan_jumbos.svg
  src/assets/volleyballTeam/hyundaicapital_skywalkers.svg
  src/assets/volleyballTeam/ok_okman.svg
  src/assets/volleyballTeam/samsung_bluefangs.svg
  src/assets/volleyballTeam/woori_one.svg
  src/common/components/atoms/TeamLogo.tsx
  src/common/constants.ts
  src/pages/admin/components/RegisteredMatches/index.tsx
Labels: ➕ add, ♻️ refactor

#120 메인페이지에서 예매하기버튼 수정, 좌석번호수정
  src/common/components/atoms/button/LinkButton.tsx
  src/common/types/seatTypes.ts
  src/pages/Home/components/MainMatch/MainMatchInfo/index.tsx
  src/pages/Home/components/WeeklyMatches/MatchCard/index.tsx
  src/pages/Reservation/components/seats/SectionOfSeats.tsx
  src/pages/Reservation/components/seats/SelectedSeat.tsx
Labels: 🐛 fix

#121 vercel.json 생성 및 기타 수정사항
  src/Router.tsx
  src/common/layouts/AccountLayout.tsx
  src/common/utils/isGameDatePast.ts
  src/pages/Login/api/useLoginMutation.ts
  src/pages/MyTicket/components/modal/CancellationConfirmModal/index.tsx
  src/pages/MyTicket/components/modal/InformationModal/InformationDetail.tsx
  src/pages/MyTicket/components/modal/InformationModal/index.tsx
  src/pages/MyTicket/hooks/useReservationDetails.ts
  src/pages/Reservation/components/PayModal.tsx
  src/pages/admin/components/DetailModal/index.tsx
  vercel.json
Labels: 💚 chore, 💄 design, 🚚 rename

#130 회원탈퇴 페이지 레이아웃 수정 및 로고 변경
  src/assets/footballTeam/daegu_fc.svg
  src/common/layouts/AuthLayout/index.tsx
  src/pages/AccountDeletion/index.tsx
Labels: 💚 chore, 💄 design

#132 마이페이지 제목 밑 설명 디자인 수정
  src/common/components/atoms/AuthFirstHeading.tsx
  src/common/layouts/AuthLayout/index.tsx
Labels: 💄 design

#134 Gyeongmin
  src/Router.tsx
  src/pages/MatchList/components/HomeInfo/RenderMap.tsx
  src/pages/MatchList/components/MatchDetailMenu/index.tsx
  src/pages/MatchList/components/MatchListTab/TeamList.tsx
  src/pages/MatchList/components/MatchListTab/index.tsx
  src/pages/Reservation/components/PayModal.tsx
  src/pages/admin/components/RegisteredMatches/index.tsx
Labels: 🐛 fix, 🎨 style, ♻️ refactor, 🔥 delete
